language: csharp
# runtime config
mono: none
dotnet: 3.1.100
dist: bionic

# branch build config
branches:
  only:
    - master
    - dev
    - preview

  except:
    - gh-pages


# git config
git:
  depth: 1
  lfs_skip_smudge: true # disable the download of LFS objects when cloning
  
script:
  - bash build.sh
