name: SonarCloudBuild
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install SonarCloud scanner
      run: |
        dotnet tool install --global dotnet-sonarscanner
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet add ./test/WeihanLi.Common.Test/WeihanLi.Common.Test.csproj package coverlet.msbuild
        dotnet test ./test/WeihanLi.Common.Test/WeihanLi.Common.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
        dotnet sonarscanner begin /k:"WeihanLi_WeihanLi.Common" /o:"weihanli" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml /d:sonar.exclusions=samples/**/*,perf/**/*,test/**/*,docs/**/,**/Models/*,**/Logging/*,**/*Logging*/*
        dotnet build
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
